"""
Resilience report — a self-contained HTML one-pager (print-to-PDF from browser).

Kept dependency-light on purpose: no wkhtmltopdf/weasyprint. Open the generated file
and Ctrl+P -> Save as PDF for the application upload.
"""
from __future__ import annotations

from jinja2 import Template

from .building import Building
from .hazard import HeatwaveResult, OutageResult

_TEMPLATE = Template("""<!doctype html>
<html><head><meta charset="utf-8"><title>Resilience Report — {{ b.name }}</title>
<style>
  body{font-family:system-ui,Segoe UI,Roboto,sans-serif;color:#0f172a;max-width:820px;margin:2rem auto;padding:0 1rem;line-height:1.5}
  h1{margin:0 0 .2rem;font-size:1.6rem} .sub{color:#64748b;margin-bottom:1.4rem}
  .score{display:inline-block;font-size:2.6rem;font-weight:800;color:{{ score_color }}}
  .band{font-weight:600;color:{{ score_color }}}
  .grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.8rem;margin:1rem 0}
  .tile{background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:.8rem}
  .tile .k{font-size:.75rem;color:#64748b;text-transform:uppercase;letter-spacing:.04em}
  .tile .v{font-size:1.3rem;font-weight:700}
  table{width:100%;border-collapse:collapse;margin:.5rem 0 1.2rem}
  th,td{text-align:left;padding:.45rem .5rem;border-bottom:1px solid #e2e8f0;font-size:.9rem;vertical-align:top}
  th{color:#475569;font-size:.72rem;text-transform:uppercase}
  h2{font-size:1.05rem;margin:1.4rem 0 .3rem;border-left:4px solid #0ea5e9;padding-left:.5rem}
  .foot{color:#94a3b8;font-size:.75rem;margin-top:2rem;border-top:1px solid #e2e8f0;padding-top:.6rem}
</style></head><body>
  <h1>ResilienceOS — Energy Resilience Report</h1>
  <div class="sub">{{ b.name }} · {{ "%.0f"|format(b.floor_area_m2) }} m² · {{ b.num_floors }} floors ·
    {{ b.solar_kwp|int }} kWp solar · {{ b.battery_kwh|int }} kWh battery</div>

  <div>Resilience Score <span class="score">{{ score.score }}</span><span style="color:#94a3b8">/100</span>
    &nbsp;<span class="band">{{ score.band }}</span></div>

  <div class="grid">
    <div class="tile"><div class="k">Peak indoor (passive)</div><div class="v">{{ "%.1f"|format(hw.peak_indoor) }}°C</div></div>
    <div class="tile"><div class="k">Peak heat index</div><div class="v">{{ "%.0f"|format(hw.peak_heat_index) }}°C</div></div>
    <div class="tile"><div class="k">Safe occupied hours</div><div class="v">{{ hw.safe_occupancy_hours }}/{{ hw.occupied_hours }}</div></div>
    <div class="tile"><div class="k">Outdoor peak</div><div class="v">{{ "%.1f"|format(hw.peak_outdoor) }}°C</div></div>
    <div class="tile"><div class="k">Hrs to unsafe (outage)</div><div class="v">{{ ("%.0f h"|format(out.hours_until_unsafe)) if out.hours_until_unsafe is not none else "safe" }}</div></div>
    <div class="tile"><div class="k">Critical-load backup</div><div class="v">{{ "%.1f"|format(out.backup_hours) }} h</div></div>
  </div>

  <h2>Operational plan — forecast heatwave day</h2>
  <table><tr><th>Time</th><th>Action</th><th>Why</th></tr>
  {% for a in plan %}<tr><td>{{ a.time }}</td><td>{{ a.action }}</td><td>{{ a.reason }}</td></tr>{% endfor %}
  </table>

  <h2>Outage response ({{ out.start_hour }}:00, {{ out.duration_h }}h)</h2>
  <table><tr><th>Step</th><th>Action</th><th>Why</th></tr>
  {% for s in seq %}<tr><td>{{ s.step }}</td><td>{{ s.action }}</td><td>{{ s.reason }}</td></tr>{% endfor %}
  </table>

  {% if copilot %}<h2>AI copilot rationale</h2><p>{{ copilot }}</p>{% endif %}

  <div class="foot">Generated by ResilienceOS · Digital twin: 5R1C ISO-13790 (rcbsim, ETH Zürich, MIT) ·
    Weather: Open-Meteo · Thresholds: NDMA/ASHRAE. Early-prototype estimates for decision support, not a substitute for on-site engineering assessment.</div>
</body></html>""")


def _score_color(score: int) -> str:
    if score >= 75: return "#16a34a"
    if score >= 50: return "#ca8a04"
    if score >= 30: return "#ea580c"
    return "#dc2626"


def render_report(b: Building, hw: HeatwaveResult, out: OutageResult,
                  score: dict, plan: list, seq: list, copilot: str | None = None) -> str:
    return _TEMPLATE.render(
        b=b, hw=hw, out=out, score=score, plan=plan, seq=seq,
        copilot=copilot, score_color=_score_color(score["score"]),
    )
